version: 2
updates:
  - package-ecosystem: docker
    directory: "/ops-bedrock"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - M-dependabot

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - M-dependabot

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - M-dependabot
