[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-Wl,-install_name,@rpath/libespresso_crypto_helper-aarch64-apple-darwin.dylib",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-Wl,-install_name,@rpath/libespresso_crypto_helper-x86_64-apple-darwin.dylib",
]
