version: "3.9"
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    command: anvil
    ports:
      - "8545:8545" # JSON-RPC
      - "8546:8546" # WebSocket (optional)
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
  espresso-dev-node:
    image: ghcr.io/espressosystems/espresso-sequencer/espresso-dev-node:20250428-dev-node-decaf-pos
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
      - "$ESPRESSO_BUILDER_PORT:$ESPRESSO_BUILDER_PORT"
      - "$ESPRESSO_DEV_NODE_PORT:$ESPRESSO_DEV_NODE_PORT"
    environment:
      - ESPRESSO_BUILDER_PORT
      - ESPRESSO_DEPLOYER_ACCOUNT_INDEX
      - ESPRESSO_DEV_NODE_PORT
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_DATABASE_MAX_CONNECTIONS=25
      - ESPRESSO_SEQUENCER_STORAGE_PATH=/data/espresso
      - RUST_LOG=info
      - RUST_LOG_FORMAT
    volumes:
      - espresso_storage:/data/espresso
    depends_on:
      - anvil

volumes:
  espresso_storage:
