name: Contract Bindings

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  contract-bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        name: Cancel Outdated Builds
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Enable Cachix
        uses: cachix/cachix-action@v15
        continue-on-error: true
        with:
          name: espresso-systems-private
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community
          skipPush: ${{ github.actor == 'dependabot[bot]' }}

      - uses: actions/checkout@v4
        name: Checkout Repository
        with:
          submodules: recursive

      - name: Generate Bindings
        run: |
          nix develop --accept-flake-config -c just bind-light-client
          git diff --exit-code
